# Generated by Django 5.1.5 on 2025-02-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_inventory_inventoryitem_inventoryitemadditionaldata_and_more'),
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventoryitempurchase',
            name='item',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='pantry_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.inventoryitem'),
        ),
        migrations.RemoveField(
            model_name='inventoryitemadditionaldata',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itempurchaseadditionaldata',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryItemAdditionalData',
        ),
        migrations.DeleteModel(
            name='InventoryItemPurchase',
        ),
        migrations.DeleteModel(
            name='ItemPurchaseAdditionalData',
        ),
    ]
